### ISSUE TITLE
Get Radius value from rectangle

### ISSUE THREAD

**Issue by chuyyei** [layervault/psd.rb#60]
Hello,

It's possible to get the radius value from a rectangle shape?

**Comment by joedivita** [comment]
@chuyyei - I had the same question.  Don't know if you ended up solving it, but with digging I found: 

```ruby
psd.tree.descendant_layers.each_with_index do |node, index|
  rounded_rect_radius_info = node.layer.info[:vector_origination].data[:keyOriginRRectRadii]      
end
```

should fetch the radii info for a rounded rect shape.
