### ISSUE TITLE
Possible to create a PSD file?

### ISSUE THREAD

**Issue by Chrisedmo** [layervault/psd.rb#80]
Sorry for the n00b question, but would it be possible to create a PSD file with this? Ideally i'd like to use this as a sketch plugin and create a PSD export option. But i doubt it's possible.

**Comment by kellysutton** [comment]
Hi @Chrisedmo, 

Unfortunately, your intuition is correct. You cannot write back to PSDs with this library yet. We're always accepting pull requests, though :)
