### ISSUE TITLE
undefined method `outset' for #<PSD::Slice>

### ISSUE THREAD

**Issue by oTiMo** [layervault/psd.rb#86]
When calling psd.tree.to_hash

    /home/tim/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/psd-3.3.2/lib/psd/slice.rb:41:in `block in to_hash'
    : undefined method `outset' for #<PSD::Slice:0xb87891d8> (NoMethodError)
	from /home/tim/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/psd-3.3.2/lib/psd/slice.rb:41:in `map'
	from /home/tim/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/psd-3.3.2/lib/psd/slice.rb:41:in `to_hash'
	from /home/tim/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/psd-3.3.2/lib/psd/nodes/root.rb:57:in `map'
	from /home/tim/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/psd-3.3.2/lib/psd/nodes/root.rb:57:in `to_hash'

**Comment by meltingice** [comment]
Ah sorry, this was fixed, but I forgot to push a new version for it. Update the gem to version 3.3.3 and it should work.

**Comment by oTiMo** [comment]
It works ! Thank you :)
